# Site settings
author: Christopher Woo
title: Journey Into Data Science
header-img: img/home-bg.png
email: cwoo90@gmail.com
copyright_name: Christopher Woo
description: > # this means to ignore newlines until "baseurl:"
  Projects
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  c-woo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
